"""MONOS Dialog Tier Design System — golden reference (visual design FROZEN).

Import components and shells from this package. Compare all new dialogs against
``Tier1Dialog`` / ``Tier2Dialog`` and the harness demos in ``scripts/test_dialog_tiers.py``.

See ``.cursor/rules/plan_dialog_tier_golden_reference_v1.mdc``.
"""

from monostudio.ui_qt.dialog_tier.dcc_picker import DccPickerCard, DccPickerGrid, DccPickerItem, ImportSourceCard
from monostudio.ui_qt.dialog_tier.reference import (
    CURRENT_THEME,
    TIERS_QSS,
    T,
    T_METRICS,
    ComboField,
    DateField,
    DialogCloseButton,
    DialogHairline,
    DialogHero,
    FieldRow,
    FieldShell,
    GhostButton,
    GradientPrimaryButton,
    InfoStrip,
    InputWithSuffix,
    MetadataCard,
    MonoSelect,
    MonoSelectItem,
    MonoSelectOption,
    PathField,
    PlainFieldInput,
    ProjectIdMetadataCard,
    Tier1Dialog,
    Tier2Dialog,
    Tier2CompactDialog,
    WorkspacePicker,
    apply_tier_app_theme,
    configure_tier_text_rendering,
    make_field_label,
    mono_select_options_from_strings,
    set_tier_theme,
    stack_field_column,
    tier_btn,
    tier_chrome_band_height,
    tier_close_button,
    tier_font,
    tier_footer_divider,
)
from monostudio.ui_qt.elevation import ELEVATION_LIGHTNESS_STEP, elevate
from monostudio.ui_qt.surfaces import (
    SEMANTIC_SURFACE_LADDER,
    SURFACE_APP,
    SURFACE_CARD,
    SURFACE_DIALOG,
    SURFACE_FIELD,
    SURFACE_OVERLAY,
    SURFACE_PARENT,
    SURFACE_POPUP,
    SURFACE_TOOLTIP,
    surface_border_color,
    surface_color,
    surface_parent,
)

__all__ = [
    "CURRENT_THEME",
    "TIERS_QSS",
    "T",
    "T_METRICS",
    "ComboField",
    "DccPickerCard",
    "DccPickerGrid",
    "DccPickerItem",
    "ImportSourceCard",
    "DateField",
    "DialogCloseButton",
    "DialogHairline",
    "DialogHero",
    "FieldRow",
    "FieldShell",
    "GhostButton",
    "GradientPrimaryButton",
    "InfoStrip",
    "InputWithSuffix",
    "MetadataCard",
    "MonoSelect",
    "MonoSelectItem",
    "MonoSelectOption",
    "PathField",
    "PlainFieldInput",
    "ProjectIdMetadataCard",
    "Tier1Dialog",
    "Tier2Dialog",
    "Tier2CompactDialog",
    "WorkspacePicker",
    "apply_tier_app_theme",
    "configure_tier_text_rendering",
    "make_field_label",
    "mono_select_options_from_strings",
    "set_tier_theme",
    "stack_field_column",
    "ELEVATION_LIGHTNESS_STEP",
    "elevate",
    "SEMANTIC_SURFACE_LADDER",
    "SURFACE_APP",
    "SURFACE_CARD",
    "SURFACE_DIALOG",
    "SURFACE_FIELD",
    "SURFACE_OVERLAY",
    "SURFACE_PARENT",
    "SURFACE_POPUP",
    "SURFACE_TOOLTIP",
    "surface_border_color",
    "surface_color",
    "surface_parent",
    "tier_btn",
    "tier_chrome_band_height",
    "tier_close_button",
    "tier_font",
    "tier_footer_divider",
]
